version: '3.8'

services:
  api:
    image: api
    build:
      context: ..
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    container_name: mis_api
    depends_on:
      - db
      - rabbitmq
      - maildev

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mis-hits
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    container_name: rabbitmq

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
    container_name: maildev

volumes:
  db_data: {}  
